# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - BookingPlatformAPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npx prisma generate

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            dist
            prisma
            package.json
            package-lock.json

  deploy:
    needs: build
    runs-on: ubuntu-latest

   
